---
- hosts: all
  tasks:
    - name: yum-clean-all
      command: yum clean all
      args:
        warn: no

    - name: 45Drives Repository - Configure 45drives repository
      get_url:
        url: http://images.45drives.com/repo/centos/45drives-centos.repo
        dest: /etc/yum.repos.d/45drives-centos.repo
        mode: '0644'

- hosts: osds
  vars:
      tools_install_dir: "/opt/45drives/tools" 
  tasks:
    - name: install tools
      package:
        name: 45drives-tools
        state: latest
      register: result
      until: result is succeeded
      
    - name: Create drive alias' for standard chassis
      command: /usr/bin/python3 "{{ tools_install_dir }}"/dmap 
      register: dmap_output

    - name: Show dmap output
      debug:
        msg: "{{ dmap_output.stdout_lines }}"
      when:
      - dmap_output.failed

    - name: Get drive layout
      command: /usr/bin/python3 "{{ tools_install_dir }}"/lsdev -n
      register: drive_layout
      changed_when: false

    - name: Show drive layout
      debug:
        msg: "{{ drive_layout.stdout_lines }}"
      when: 
      - not drive_layout.failed

- name: Import generate-osd-vars playbook
  import_playbook: generate-osd-vars.yml

