---
- hosts: osds
  tasks:
    - name: 45Drives Repository - Configure 45drives repository
      yum_repository:
        name: ceph_45drives
        description: 45Drives $basearch repo
        gpgcheck: no
        enabled: yes
        state: present
        baseurl: "{{ ceph_45drives_repo_url }}"
        file: ceph_45drives
        priority: "1"
      register: result
      until: result is succeeded

    - name: install tools
      package:
        name: 45drives-tools
        state: latest
      register: result
      until: result is succeeded

- hosts: osds
  vars:
      tools_install_dir: "/opt/tools" 
  tasks:
    - name: Create drive alias' for standard chassis
      command: /usr/bin/python3 "{{ tools_install_dir }}"/dmap 
      register: dmap_output

    - name: Show dmap output
      debug:
        msg: "{{ dmap_output.stdout_lines }}"
      when:
      - dmap_output.failed

    - name: Get drive layout
      command: /usr/bin/python3 "{{ tools_install_dir }}"/lsdev -n
      register: drive_layout
      changed_when: false

    - name: Show drive layout
      debug:
        msg: "{{ drive_layout.stdout_lines }}"
      when: 
      - not drive_layout.failed

- name: Import generate-osd-vars playbook
  import_playbook: generate-osd-vars.yml

