---
- hosts: osds
  tasks:
    - name: execute generate-osd-vars script
      command: /usr/bin/bash /opt/45drives/tools/generate-osd-vars.sh
      register: output

    - debug:
         msg: "{{ output.stdout }}"

    - local_action: file path=/usr/share/ceph-ansible/host_vars/ state=directory
      when: not output.failed

    - local_action: copy content={{ output.stdout }} dest=/usr/share/ceph-ansible/host_vars/{{ inventory_hostname }}.yml
      when: not output.failed
