---
- hosts: all
  tasks:
    - name: Install Extra Dependencies in Ubuntu 
      block:
        - name: Install Extra Dependencies in Ubuntu 
          debug:
            msg: "--"
      when:
        - ansible_distribution == 'Ubuntu'

    - name: Install Extra Dependencies in CentOS7
      block:
        - name: Install Extra Dependencies in CentOS7
          yum:
            name: ['python36-six', 'python36-PyYAML']
            state: absent
          register: result
          until: result is succeeded          
      when:
        - ansible_distribution == 'CentOS'
        - ansible_distribution_major_version == '7'
