---
- name: configure_cephfs_backend | Create directory for samba shares
  shell: /usr/local/bin/cephfs-shell "mkdir -m 755 -p /fsgw"
  delegate_to: "{{ groups[mon_group_name][0] }}"
  run_once: true

- name: configure_cephfs_backend | Create samba cephx user
  ceph_key:
    name: "{{ item.name }}"
    state: present
    caps: "{{ item.caps }}"
    cluster: "{{ cluster }}"
    secret: "{{ item.key | default('') }}"
  with_items: "{{ samba_keyring }}"
  delegate_to: "{{ groups[mon_group_name][0] }}"

- name: configure_cephfs_backend | Get samba secret for cephfs mount
  command: "ceph auth get-key client.samba"
  register: command_output_samba
  delegate_to: "{{ groups[mon_group_name][0] }}"
  changed_when: false

- name: configure_cephfs_backend | Set samba secret fact
  set_fact:
    cephfs_samba_secret: "{{ command_output_samba.stdout }}"

- name: configure_cephfs_backend | write ceph samba client secret
  copy:
    content: "{{ cephfs_samba_secret }}"
    dest: /etc/ceph/samba.secret
    force: yes
    group: ceph
    owner: ceph
    mode: "0600"

- name: configure_cephfs_backend | Get samba keyring for rados locking
  command: "ceph auth get client.samba"
  register: samba_keyring
  delegate_to: "{{ groups[mon_group_name][0] }}"
  changed_when: false

- name: configure_cephfs_backend | Write samba keyring
  copy:
    content: "{{ samba_keyring.stdout }}\n"
    dest: "/etc/ceph/{{cluster}}.client.samba.keyring"
    force: yes
    group: ceph
    owner: ceph
    mode: "0600"

- name: configure_cephfs_backend | mount {{ shared_storage_mountpoint }}/fsgw
  mount:
    name: "{{ shared_storage_mountpoint }}/fsgw"
    src: "{{ groups[mon_group_name][0] }}:/fsgw"
    fstype: "ceph"
    opts: "name=samba,secretfile=/etc/ceph/samba.secret,_netdev,noatime"
    state: mounted

