---
- name: configure_cephfs_backend | mount {{ shared_storage_mountpoint }}/fsgw
  mount:
    name: "{{ shared_storage_mountpoint }}/fsgw"
    src: "{{ groups[mon_group_name][0] }}:/fsgw"
    fstype: "ceph"
    opts: "name=samba,secretfile=/etc/ceph/samba.secret,_netdev,relatime"
    state: mounted

- name: configure_kernel_shares - Ensure share directory exists
  file:
    path: "{{ shared_storage_mountpoint }}/fsgw/{{ item.name }}"
    owner: "root"
    group: "root"
    mode: '0775'
    state: directory
  run_once: true
  with_items:
    - "{{ samba_shares }}"

# If using vfs_cephfs, use relative paths 
- name: vfs_ceph share configuration
  block:
  - name: configure_vfs_shares - create shares
    shell: net conf addshare {{ item.name }} /fsgw/{{ item.name }} writeable={{ item.writeable[:1] }} guest_ok={{ item.guest_ok[:1] }} "{{ item.comment }}"
    failed_when: false
    run_once: true
    loop: "{{ samba_shares }}"

  - name: configure_vfs_shares - add parameters vfs_objects
    shell: net conf setparm {{ item.name }} "vfs objects" ceph
    failed_when: false
    run_once: true
    loop: "{{ samba_shares }}"
  
  - name: configure_vfs_shares - add parameters kernel share modes
    shell: net conf setparm {{ item.name }} "kernel share modes" no
    failed_when: false
    run_once: true   
    loop: "{{ samba_shares }}"

  - name: configure_vfs_shares - add parameters ceph config
    shell: net conf setparm {{ item.name }} ceph:config_file /etc/ceph/ceph.conf
    failed_when: false
    run_once: true
    loop: "{{ samba_shares }}"
  
  - name: configure_vfs_shares - add parameters ceph user
    shell: net conf setparm {{ item.name }} ceph:user_id samba
    failed_when: false
    run_once: true
    loop: "{{ samba_shares }}"

- name: configure_vfs_shares - Domain Member Windows ACL 
  block:
    - name: configure_vfs_shares - Grant the SeDiskOperatorPrivilege Privilege
      shell: net sam rights grant "{{ active_directory_info.ad_admin_group }}" SeDiskOperatorPrivilege -U "{{ active_directory_info.domain_join_user }}"%"{{ active_directory_info.domain_join_password }}"
      run_once: true

    - name: configure_vfs_shares - Update directory ownership
      file:
        path: "{{ shared_storage_mountpoint }}/fsgw/{{ item.name }}"
        owner: "root"
        group: '{{ active_directory_info.workgroup|upper }}\{{ active_directory_info.ad_admin_group }}'
        mode: '0770'
        state: directory
      run_once: true
      with_items:
        - "{{ samba_shares }}"
  when:
    - windows_acl | bool
    - domain_member | bool

- name: configure_cephfs_backend | unmount {{ shared_storage_mountpoint }}/fsgw
  mount:
    name: "{{ shared_storage_mountpoint }}/fsgw"
    src: "{{ groups[mon_group_name][0] }}:/fsgw"
    fstype: "ceph"
    opts: "name=samba,secretfile=/etc/ceph/samba.secret,_netdev,relatime"
    state: absent
