---
- name: install container packages on each node
  block:
    - name: check if it is Atomic host
      stat: path=/run/ostree-booted
      register: stat_ostree
      check_mode: no

    - name: set_fact is_atomic
      set_fact:
        is_atomic: '{{ stat_ostree.stat.exists }}'
      tags: always
    - import_role:
        name: ceph-container-engine

- name: include specific variables
  include_vars: "../../ceph-container-engine/vars/{{ item }}"
  with_first_found:
    - "{{ ansible_facts['distribution'] }}-{{ ansible_facts['distribution_major_version'] }}.yml"
    - "{{ ansible_facts['os_family'] }}.yml"

- name: import container images w. podman
  include_tasks: offline/import_container_images_podman.yml
  when: "{{ container_service_name }}" == "podman" 

- name: import container images w. docker
  include_tasks: offline/import_container_images_podman.yml
  when: "{{ container_service_name }}" == "docker" 

