---
- name: Inspect node_exporter local image
  podman_image_info:
    name: "{{ node_exporter_container_image }}"
  register: node_exporter_result

- name: Pull down and import node_exporter image if not present already
  include_tasks: image_import.yml
  loop: "{{ node_exporter_container_image_archive }}"
  when: node_exporter_result.images | length == 0

- name: Inspect metrics node for local docker images
  podman_image_info:
    name: "{{ metric_container_images }}"
  register: metric_images_result

- name: Pull down and import node_exporter image if not present already
  include_tasks: image_import.yml
  loop: "{{ metric_container_images_archive|flatten(levels=1) }}"
  delegate_to: "{{ groups[grafana_server_group_name][0] }}"
  when: metric_images_result.images | length != 3
