---

- name: check if sources.list exists
  stat:
    path: /etc/apt/sources.list
  register: ubuntu_repo_result

- name: disable ubuntu main repos
  block:
    - name: create backup of sources.list
      copy: remote_src=True src=/etc/apt/sources.list dest=/etc/apt/sources.list.bak

    - name: remove sources.list
      file: path=/etc/apt/sources.list state=absent

  when: ubuntu_repo_result.stat.exists == True

- name: check if 45drives.sources exists
  stat:
    path: /etc/apt/sources.list.d/45drives.sources
  register: ffd_repo_result

- name: disable 45drives repo
  block:
    - name: create backup of 45drives.sources
      copy: remote_src=True src=/etc/apt/sources.list.d/45drives.sources dest=/etc/apt/sources.list.d/45drives.sources.bak

    - name: remove 45drives.sources
      file: path=/etc/apt/sources.list.d/45drives.sources state=absent
  when: ffd_repo_result.stat.exists == True

- name: place offline repo file on each node
  template:
    src: "ubuntu-offline.list.j2"
    dest: "/etc/apt/sources.list.d/ubuntu-offline.list"
    owner: root
    group: root
    mode: 0644

- name: import apt keys for ceph, nfs-ganeha and 45drives
  apt_key:
    url: http://{{ offline_repo_server_ip }}/keys/{{ item }}.asc
    state: present
  loop:
    - 45drives
    - ceph
    - nfs-ganesha
    - docker-ce

- name: update apt cache
  apt:
    update_cache: yes

- name: install container packages on each node
  block:
    - name: check if it is Atomic host
      stat: path=/run/ostree-booted
      register: stat_ostree
      check_mode: no

    - name: set_fact is_atomic
      set_fact:
        is_atomic: '{{ stat_ostree.stat.exists }}'
      tags: always
    - import_role:
        name: ceph-container-engine

- name: Inspect node_exporter local image
  docker_image_info:
    name:
      - prom/node-exporter:v0.17.0
  register: node_exporter_result

- name: Pull down and import node_exporter image if not present already
  block:
    - name: Pull down node_exporter image
      get_url:
        url: http://{{ offline_repo_server_ip }}/images/node-exporter-v0.17.0.tar
        dest: /tmp/node-exporter-v0.17.0.tar

    - name: Import node_exporter if not present already
      shell: "/usr/bin/docker load -i /tmp/node-exporter-v0.17.0.tar"

    - name: remove node-exporter image tar
      file:
        path: /tmp/node-exporter-v0.17.0.tar
        state: absent
  when: node_exporter_result.images | length == 0

- name: Inspect metrics node for local docker images
  docker_image_info:
    name:
      - localhost/grafana-offline:5.4.2
      - prom/alertmanager:v0.16.2
      - prom/prometheus:v2.7.2
  register: metric_images_result

- name: Pull down and import metric stack images if not present already
  block:
    - name: Pull down node_exporter image
      get_url:
        url: http://{{ offline_repo_server_ip }}/images/{{ item }}
        dest: /tmp/{{ item }}
      loop: "{{ metric_docker_images|flatten(levels=1) }}"

    - name: Import node_exporter if not present already
      shell: "/usr/bin/docker load -i /tmp/{{ item }}"
      loop: "{{ metric_docker_images|flatten(levels=1) }}"

    - name: remove node-exporter image tar
      file:
        path: /tmp/{{ item }}
        state: absent
      loop: "{{ metric_docker_images|flatten(levels=1) }}"
  delegate_to: "{{ groups[grafana_server_group_name][0] }}"
  when: metric_images_result.images | length != 3
