---
ubuntu_install_pkgs:
  - "45drives-tools"

centos_install_pkgs:
  - "45drives-tools"
  - "python36-six"
  - "python36-PyYAML"
  
rocky_install_pkgs:
  - "45drives-tools"

ubuntu_cleanup_pkgs:
  - "zfs-dkms"
  - "zfsutils-linux"
  - "libzfs2linux"
  - "libzfslinux-dev"
  - "cockpit-zfs-manager"
  - "cockpit-machines"

centos_cleanup_pkgs:
  - "zfs" 
  - "cockpit-zfs-manager"
  - "cockpit-machines"

rocky_cleanup_pkgs:
  - "zfs"
  - "cockpit-zfs-manager"
  - "cockpit-machines"


