---
- name: Configure 45Drives repository | Get repo setup script
  get_url:
    url: https://repo.45drives.com/setup
    dest: /tmp/setup

- name: Configure 45Drives repository | Remove repo setup script
  file:
    path: /tmp/setup
    state: absent

- name: Configure 45Drives repository | Run repo setup script
  shell: /tmp/setup
  executable: /bin/bash

- name: include_tasks cleanup/cleanup_on_ubuntu.yml
  include_tasks: cleanup/cleanup_on_ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: include_tasks cleanup/cleanup_on_centos7.yml
  include_tasks: cleanup/cleanup_on_centos7.yml
  when:
    - ansible_distribution == 'CentOS'
    - ansible_distribution_major_version == '7'

- name: include_tasks cleanup/cleanup_on_rocky8.yml
  include_tasks: cleanup/cleanup_on_rocky8.yml
  when:
    - ansible_distribution == 'Rocky'
    - ansible_distribution_major_version == '8'

- name: include_tasks install/install_on_ubuntu.yml
  include_tasks: install/install_on_ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: include_tasks install/install_on_centos7.yml
  include_tasks: install/install_on_centos7.yml
  when:
    - ansible_distribution == 'CentOS'
    - ansible_distribution_major_version == '7'
    
- name: include_tasks install/install_on_rocky8.yml
  include_tasks: install/install_on_rocky8.yml
  when:
    - ansible_distribution == 'Rocky'
    - ansible_distribution_major_version == '8'
