---
- name: include_tasks cleanup/cleanup_on_ubuntu.yml
  include_tasks: cleanup/cleanup_on_ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: include_tasks cleanup/cleanup_on_centos7.yml
  include_tasks: cleanup/cleanup_on_centos7.yml
  when:
    - ansible_distribution == 'CentOS'
    - ansible_distribution_major_version == '7'

- name: include_tasks install/install_on_ubuntu.yml
  include_tasks: install/install_on_ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: include_tasks install/install_on_centos7.yml
  include_tasks: install/install_on_centos7.yml
  when:
    - ansible_distribution == 'CentOS'
    - ansible_distribution_major_version == '7'
