---
- name: Install samba packages
  block:
    - name: install samba
      package:
        name: "{{ item }}"
        state: "{{ (upgrade_samba_packages|bool) | ternary('latest','present') }}"
      register: result
      until: result is succeeded
      with_items:
        - attr
        - samba
        - samba-vfs-cephfs
        - samba-common-tools
      when:
        - samba_server | bool

    - name: install packages for domain integration
      package:
        name: "{{ item }}"
        state: "{{ (upgrade_samba_packages|bool) | ternary('latest','present') }}"
      register: result
      until: result is succeeded
      with_items:
        - samba-winbind
        - samba-winbind-clients
        - oddjob
        - oddjob-mkhomedir
        - krb5-workstation
      when:
        - domain_member | bool

    - name: install ctdb
      package:
        name: ctdb
        state: "{{ (upgrade_samba_packages|bool) | ternary('latest','present') }}"
      register: result
      until: result is succeeded
      when:
        - samba_cluster | bool
