---
- name: Install samba packages
  block:
    - name: Ubuntu | install samba
      apt:
        pkg:
        - samba-common
        - samba-common-bin
        - samba-libs
        - libsmbclient
        - samba
        - smbclient
        - python3-samba
        - ctdb
        - winbind
        - libwbclient0
        - samba-vfs-modules
        - samba-dsdb-modules
        - libldb2
        - libnss-winbind
        - libpam-winbind
        - python3-ldb
        - krb5-config
        - oddjob
        - oddjob-mkhomedir
        state: "present"
        force: true
      register: result
      until: result is succeeded
