---
- name: Remove Samba (2:4.11.6+dfsg-0ubuntu1.6) Packages
  block:
    - name: Ubuntu | Remove samba Samba (2:4.11.6+dfsg-0ubuntu1.6)
      apt:
        name: "{{ item }}=2:4.11.6+dfsg-0ubuntu1.6"
        state: "absent"
        purge: yes
        autoremove: yes
        autoclean: yes
      register: result
      until: result is succeeded
      with_items:
        - samba-common
        - samba-common-bin
        - samba
        - libwbclient
        - samba-libs
        - python3-samba
        - winbind
        - ctdb

- name: Install samba packages
  block:
    - name: Ubuntu | install samba
      apt:
        name: "{{ item }}"
        state: "present"
      register: result
      until: result is succeeded
      with_items:
        - samba-common=2:4.11.6+dfsg-0ubuntu1
        - samba-common-bin=2:4.11.6+dfsg-0ubuntu1
        - samba-dsdb-modules=2:4.11.6+dfsg-0ubuntu1
        - samba-libs=2:4.11.6+dfsg-0ubuntu1
        - libsmbclient=2:4.11.6+dfsg-0ubuntu1
        - samba=2:4.11.6+dfsg-0ubuntu1
        - samba-libs=2:4.11.6+dfsg-0ubuntu1
        - python3-samba=2:4.11.6+dfsg-0ubuntu1
        - winbind=2:4.11.6+dfsg-0ubuntu1
        - libwbclient0=2:4.11.6+dfsg-0ubuntu1
        - ctdb=2:4.11.6+dfsg-0ubuntu1
        - oddjob
        - oddjob-mkhomedir

- name: Hold samba packages at version 2:4.11.6+dfsg-0ubuntu1
  block:
    - name: Ubuntu | hold samba package versions
      dpkg_selections:
          name: "{{ item }}"
          selection: hold
      with_items:
        - samba-common=2:4.11.6+dfsg-0ubuntu1
        - samba-common-bin=2:4.11.6+dfsg-0ubuntu1
        - libsmbclient=2:4.11.6+dfsg-0ubuntu1
        - samba=2:4.11.6+dfsg-0ubuntu1
        - samba-libs=2:4.11.6+dfsg-0ubuntu1
        - python3-samba=2:4.11.6+dfsg-0ubuntu1
        - winbind=2:4.11.6+dfsg-0ubuntu1
        - libwbclient0=2:4.11.6+dfsg-0ubuntu1
        - ctdb=2:4.11.6+dfsg-0ubuntu1