---
- name: Install samba packages
  block:
    - name: Ubuntu | install samba
      apt:
        pkg:
        - samba-common=2:4.11.6+dfsg-0ubuntu1
        - samba-common-bin=2:4.11.6+dfsg-0ubuntu1
        - samba-libs=2:4.11.6+dfsg-0ubuntu1
        - libsmbclient=2:4.11.6+dfsg-0ubuntu1
        - samba=2:4.11.6+dfsg-0ubuntu1
        - python3-samba=2:4.11.6+dfsg-0ubuntu1
        - winbind=2:4.11.6+dfsg-0ubuntu1
        - libwbclient0=2:4.11.6+dfsg-0ubuntu1
        - ctdb=2:4.11.6+dfsg-0ubuntu1
        - samba-vfs-modules=2:4.11.6+dfsg-0ubuntu1
        - oddjob
        - oddjob-mkhomedir
        state: "present"
      register: result
      until: result is succeeded

- name: Hold samba packages at version 2:4.11.6+dfsg-0ubuntu1
  block:
    - name: Ubuntu | hold samba package versions
      dpkg_selections:
          name: "{{ item }}"
          selection: hold
      with_items:
        - samba-common
        - samba-common-bin
        - samba-libs
        - libsmbclient
        - samba
        - python3-samba
        - winbind
        - libwbclient0
        - ctdb
        - samba-vfs-modules