---
- name: config_domain | configuring krb5.conf
  template:
    src: "etc/krb5.conf.j2"
    dest: "/etc/krb5.conf"
    owner: root
    group: root
    mode: 0644

- name: config_domain | configure domain user login
  block:
    - name: config_domain | use authselect to configure nsswitch.conf
      shell: "/usr/bin/authselect select winbind with-mkhomedir --force"
    
    - name: start_config_domain | enable oddjobd
      systemd:
        name: oddjobd
        state: started
        enabled: yes

- name: config_domain | Standalone
  block:
      # net ads testjoin -k will check if domain is already joined or not
      # returns: 255 -> Not in Domain, 0 -> In domain
    - name: config_domain | checking if already joined to domain
      shell: "net ads testjoin -k"
      ignore_errors: true
      register: domain_check

    - name: config_domain | joining domain
      shell: net ads join -U "{{ active_directory_info.domain_join_user }}"%"{{ active_directory_info.domain_join_password }}"
      register: "domain_joined"
      when: domain_check.rc == 255

    - name: start_config_domain | enable samba
      systemd:
        name: smb
        state: started
        enabled: yes

    - name: start_config_domain | enable winbind
      systemd:
        name: winbind
        state: started
        enabled: yes
  when:
    - not samba_cluster | bool

- name: config_domain | Cluster
  block:
    - name: config_domain | ensure ctdb is started
      service:
        name: "ctdb"
        state: started
        enabled: yes
      register: "ctdb_started"

    - name: config_domain | waiting for ctdb to start
      wait_for:
        delay: 5 
        host: "{{ ansible_default_ipv4.address }}"
        port: 4379
      when: ctdb_started.changed

      # net ads testjoin -k will check if domain is already joined or not
      # returns: 255 -> Not in Domain, 0 -> In domain
    - name: config_domain | checking if already joined to domain
      shell: "net ads testjoin -k"
      failed_when: false
      register: domain_check

    - name: config_domain | joining domain
      shell: net ads join -U "{{ active_directory_info.domain_join_user }}"%"{{ active_directory_info.domain_join_password }}"
      run_once: true
      register: domain_joined
      when: domain_check.rc == 255

    - name: config_domain | restarting ctdb #we do this after joining the domain in order to get winbind started
      service:
        name: "ctdb"
        state: restarted
      when: domain_check.rc == 255
      register: "ctdb_restarted"

    - name: config_domain | waiting for ctdb to restart
      wait_for:
        delay: 20
        host: "{{ ansible_default_ipv4.address }}"
        port: 4379
      when: ctdb_restarted.changed
  when:
    - samba_cluster | bool

- name: Grant the SeDiskOperatorPrivilege Privilege for windows ACLs
  shell: net rpc rights grant "{{ active_directory_info.workgroup|upper }}\{{ active_directory_info.ad_admin_group }}" SeDiskOperatorPrivilege -U "{{ active_directory_info.domain_join_user }}"%"{{ active_directory_info.domain_join_password }}"
  run_once: true
  when:
    - enable_windows_acl | bool

