---
- name: 45Drives Repository - Configure 45drives repository
  get_url:
    url: http://images.45drives.com/repo/centos/45drives-centos.repo
    dest: /etc/yum.repos.d/45drives-centos.repo
    mode: '0644'
  when: '"45drives" in samba_repo'

- name: Community Repository - Check if samba_45drives repo is present; remove if it is
  block:
  - name: Community Repository - Check if samba_45drives repo is present
    stat:
      path: /etc/yum.repos.d/samba_45drives.repo
    register: stat_result
    when: '"community" in samba_repo'

  - name: Community Repository - Remove samba_45drives repository (and clean up left-over metadata)
    yum_repository:
      name: samba_45drives
      state: absent
    when: '"community" in samba_repo'
  
  - name: Community Repository - yum-clean-metadata
    command: yum clean metadata
    args:
      warn: no
    when: '"community" in samba_repo'

- name: Install samba packages
  block:
    - name: install samba
      package:
        name: "{{ item }}"
        state: "{{ (upgrade_samba_packages|bool) | ternary('latest','present') }}"
      register: result
      until: result is succeeded
      with_items:
        - attr
        - samba
        - samba-vfs-cephfs
        - samba-common-tools
      when:
        - samba_server | bool

    - name: install packages for domain integration
      package:
        name: "{{ item }}"
        state: "{{ (upgrade_samba_packages|bool) | ternary('latest','present') }}"
      register: result
      until: result is succeeded
      with_items:
        - samba-winbind
        - samba-winbind-clients
        - oddjob
        - oddjob-mkhomedir
        - krb5-workstation
      when:
        - domain_member | bool

    - name: install ctdb
      package:
        name: ctdb
        state: "{{ (upgrade_samba_packages|bool) | ternary('latest','present') }}"
      register: result
      until: result is succeeded
      when:
        - samba_cluster | bool
