---
# Install packages
- include: install_redhat_samba.yml

- include: configure_cephfs_backend.yml
  when: 
   - backend_fs == 'cephfs'
  
# Configure samba + winbind
- include: configure_samba.yml
  when:
    - samba_server | bool

# Configure CTDB
- include: configure_ctdb.yml
  when:
    - samba_cluster | bool

# Join Active Directory
- include: configure_domain.yml
  when:
    - domain_member | bool
  
- include: start_samba_server.yml
  when:
    - not domain_member | bool

# Configure shares
- include: configure_vfs_shares.yml
  when:
    - configure_shares | bool
    - samba_cephfs_module | bool

- include: configure_kernel_shares.yml
  when:
    - configure_shares | bool
    - not samba_cephfs_module | bool

- include: show_ctdb_status.yml
  when:
    - samba_cluster | bool