---
# Install packages
- include: install/redhat_samba.yml
  when:
    - ansible_facts['os_family'] == 'RedHat'

- include: install/ubuntu_samba.yml
  when: ansible_facts['distribution'] == 'Ubuntu'

- include: configure/cephfs_backend.yml
  when: 
   - backend_fs == 'cephfs'
  
# Configure samba + winbind
- include: configure/samba.yml
  when:
    - samba_server | bool

# Configure CTDB
- include: configure/ctdb.yml
  when:
    - samba_cluster | bool

# Join Active Directory
- include: configure/domain.yml
  when:
    - domain_member | bool
  
- include: configure/start_samba_server.yml
  when:
    - not domain_member | bool

# TODO Turn on WSD service

# Mount Cephfs on SMB gw's
# For use with houston file-sharing 
- include: mount_cephfs.yml
  when:
    - not configure_shares | bool

# Configure shares
- include: loop_shares.yml
  when:
    - configure_shares | bool

- include: show_ctdb_status.yml
  when:
    - samba_cluster | bool

