---
- name: mount_cephfs | create share directory "{{ smb_gw_path }}" on cephfs
  shell: /usr/bin/cephfs-shell "mkdir -m 755 -p {{ smb_gw_path }}"
  delegate_to: "{{ groups[mon_group_name][0] }}"
  run_once: true

- name: mount_cephfs | create local directory for share mount
  file:
    path: "{{ shared_storage_mountpoint }}"
    owner: "root"
    group: "root"
    mode: '0775'
    state: directory
  run_once: true

- name: mount_cephfs | mount share
  mount:
    name: "{{ shared_storage_mountpoint }}"
    src: ":{{ smb_gw_path }}"
    fstype: "ceph"
    opts: "name=samba,secretfile=/etc/ceph/samba.secret,_netdev,relatime"
    state: mounted